CONTIKI_PROJECT = my-project

all: $(CONTIKI_PROJECT)

CONTIKI= ../..

APPS += powertrace
	

	
CFLAGS +=-DPROJECT_CONF_H=\"project-conf.h\"
#	PROJECT_SOURCEFILES += hello_world.c
include $(CONTIKI)/Makefile.include 

